spring:
  application:
    name: cqjtu-store
  profiles:
    active: dev

#server.port=6081
#
#spring.datasource.username=root
#spring.datasource.password=wangjing
#spring.datasource.url=jdbc:mysql://localhost:3306/storedb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

